CREATE DATABASE IF NOT EXISTS `pochetesenai` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `pochetesenai`;

CREATE TABLE cursos (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  numero VARCHAR(255) NOT NULL
);

CREATE TABLE professores (
  matricula INT NOT NULL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL
);

CREATE TABLE salas (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL
);

CREATE TABLE pochetes (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sala_id BIGINT NOT NULL,
  idtoken VARCHAR(8) UNIQUE,
  CONSTRAINT fk_sala FOREIGN KEY (sala_id) REFERENCES salas(id)
);

CREATE TABLE admins (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL
);

CREATE TABLE usuarios (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL
);

CREATE TABLE dados_temporarios (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  conteudo1 INT,
  conteudo2 BIGINT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE movimentacoes (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  professor_matricula INT NOT NULL,
  pochete_id BIGINT NOT NULL,
  cursos_id BIGINT DEFAULT NULL,
  data_retirada TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  data_devolucao TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT movimentacoes_ibfk_1 FOREIGN KEY (professor_matricula) REFERENCES professores(matricula),
  CONSTRAINT movimentacoes_ibfk_2 FOREIGN KEY (pochete_id) REFERENCES pochetes(id),
  CONSTRAINT fk_movimentacoes_cursos FOREIGN KEY (cursos_id) REFERENCES cursos(id) ON DELETE SET NULL
);
